webapp/routes/web.php
<?php
/**
 *  Copyright 2020-2021 Aston University
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false, 'reset' => false, 'password.request' => false]);

Route::get('/', 'HomeController@index')->name('home');

// COLOR PREFERENCES

Route::post('/theme/toggle', 'ThemeController@toggle')->name('theme.toggle');

// TOKEN MANAGEMENT

Route::get('/tokens', 'Auth\TokenManagementController@show')->name('tokens.show');
Route::delete('/tokens/{token}', 'Auth\TokenManagementController@destroy')->name('tokens.destroy');

// ADMIN MODE

Route::get('/admin/enable', 'AdminController@enable');
Route::post('/admin/enable', 'AdminController@enable')->name('enableAdmin');
Route::get('/admin/disable', 'AdminController@disable');
Route::post('/admin/disable', 'AdminController@disable')->name('disableAdmin');

// JOBS

Route::resource('jobs', 'JobController')->only([
    'index', 'show', 'destroy', 'store', 'create'
]);

Route::get('/jobs/{job}/results/{source}/{path}', 'JobController@showResult')
    ->name('jobs.showResult')
    ->where('path', '.*');

Route::get('/jobs/{job}/download', 'JobController@download')
    ->name('jobs.download');

Route::delete('/jobs', 'JobController@destroyMany')
    ->name('jobs.destroyMany');

// MODULES

Route::resource('modules', 'TeachingModuleController');

Route::post('/modules/{module}/switchRole', 'TeachingModuleController@switchRole')
    ->name('modules.switchRole');

Route::get('/modules/{module}/users/autocomplete', 'TeachingModuleUserController@autocomplete')
    ->name('modules.users.autocomplete');

Route::delete('/modules/{module}/users', 'TeachingModuleUserController@destroyMany')
    ->name('modules.users.destroyMany');

Route::get('/modules/{module}/users/import', 'TeachingModuleUserController@importForm')
    ->name('modules.users.importForm');
Route::post('/modules/{module}/users/import', 'TeachingModuleUserController@import')
    ->name('modules.users.import');

Route::resource('modules.users', 'TeachingModuleUserController');

Route::resource('modules.items', 'TeachingModuleItemController')->except(['index']);

Route::get(
    '/modules/{module}/items/{item}/copy',
    'TeachingModuleItemController@copyForm'
)->name('modules.items.copyForm');

Route::post(
    '/modules/{module}/items/{item}/copy',
    'TeachingModuleItemController@copy'
)->name('modules.items.copy');

// MODEL SOLUTION

Route::get(
    '/modules/{module}/assessments/{assessment}/solution',
    'AssessmentController@showModelSolution'
)->name('modules.assessments.showModelSolution');

Route::post(
    '/modules/{module}/assessments/{assessment}/solution',
    'AssessmentController@storeModelSolution'
)->name('modules.assessments.storeModelSolution');

Route::delete(
    '/modules/{module}/assessments/{assessment}/solution',
    'AssessmentController@destroyModelSolution'
)->name('modules.assessments.destroyModelSolution');

// FILE OVERRIDES

Route::get(
    '/modules/{module}/assessments/{assessment}/overrides',
    'AssessmentController@showOverrides'
)->name('modules.assessments.showOverrides');

Route::post(
    '/modules/{module}/assessments/{assessment}/overrides',
    'AssessmentController@storeOverrides'
)->name('modules.assessments.storeOverrides');

// SUBMISSIONS TABLE

Route::get(
    '/modules/{module}/assessments/{assessment}/submissions',
    'AssessmentController@showSubmissions'
)->name('modules.assessments.showSubmissions');

Route::post(
    '/modules/{module}/assessments/{assessment}/submissions/rerun',
    'AssessmentController@rerunSubmissions'
)->name('modules.assessments.rerunSubmissions');

Route::get(
    '/modules/{module}/assessments/{assessment}/submissions/csv',
    'AssessmentController@downloadSubmissionsCSV'
)->name('modules.assessments.downloadSubmissionsCSV');

// SUBMISSIONS COMPARISON

Route::get(
    '/modules/{module}/assessments/{assessment}/submissions/compare',
    'AssessmentSubmissionComparisonController@showCSVForm'
)->name('modules.assessments.compare.showCSVForm');

Route::post(
    '/modules/{module}/assessments/{assessment}/submissions/compare',
    'AssessmentSubmissionComparisonController@processCSV'
)->name('modules.assessments.compare.processCSV');

// ASSESSMENT TESTS

Route::get(
    '/modules/{module}/assessments/{assessment}/tests',
    'AssessmentController@showTests'
)->name('modules.assessments.showTests');

Route::get(
    '/modules/{module}/assessments/{assessment}/tests/edit',
    'AssessmentController@editTests'
)->name('modules.assessments.editTests');

Route::post(
    '/modules/{module}/assessments/{assessment}/tests',
    'AssessmentController@storeTests'
)->name('modules.assessments.storeTests');

Route::get(
    '/modules/{module}/assessments/{assessment}/tests/yaml',
    'AssessmentController@exportTestsToYAML'
)->name('modules.assessments.exportTestsToYAML');

Route::get(
    '/modules/{module}/assessments/{assessment}/tests/yaml/import',
    'AssessmentController@showImportTestsFromYAML'
)->name('modules.assessments.showImportTestsFromYAML');

Route::post(
    '/modules/{module}/assessments/{assessment}/tests/yaml/import',
    'AssessmentController@importTestsFromYAML'
)->name('modules.assessments.importTestsFromYAML');

// PROGRESS CHART

Route::get(
    '/modules/{module}/assessments/{assessment}/progress/chart',
    'AssessmentController@viewProgressChart'
)->name('modules.assessments.viewProgressChart');

Route::get(
    '/modules/{module}/assessments/{assessment}/progress/stats',
    'AssessmentController@jsonProgressStats'
)->name('modules.assessments.jsonProgressChart');

Route::get(
    '/modules/{module}/assessments/{assessment}/progress/entries/{className}/{testName}/{status}',
    'AssessmentController@jsonClassTestStatus'
)->name('modules.assessments.jsonClassTestStatus');

// SINGLE SUBMISSION MANAGEMENT

Route::post(
    '/modules/{module}/assessments/{assessment}/storeSubmission',
    'AssessmentController@storeSubmission'
)->name('modules.assessments.storeSubmission');

Route::get(
    '/modules/{module}/submissions/{submission}',
    'AssessmentSubmissionController@show'
)->name('modules.submissions.show');

Route::post(
    '/modules/{module}/submissions/{submission}/rerun',
    'AssessmentSubmissionController@rerun'
)->name('modules.submissions.rerun');

Route::delete(
    '/modules/{module}/submissions/{submission}',
    'AssessmentSubmissionController@destroy'
)->name('modules.submissions.destroy');

// HELP PAGES

Route::view(
    '/help/markdown/conditionals',
    'help.markdown_conditionals'
)->name('help.markdown.conditionals');

webapp/resources/views/modules/create.blade.php
@php
    /**
     *  Copyright 2020 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@section('title')
    @isset($module)
        Edit Module
    @else
        Create Module
    @endisset
@endsection

@section('content')
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="text-center">
                    @isset($module)
                        Edit Module
                    @else
                        Create Module
                    @endisset
                </h2>

                <form method="POST" @isset($module) action="{{ route('modules.update', $module->id) }}"
                      @else action="{{ route('modules.store') }}" @endisset>
                    @csrf
                    @isset($module)
                        @method('PUT')
                    @endisset

                    <div class="form-group row">
                        <label for="moduleName">{{ __('Module name') }}</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" id="moduleName"
                               name="name" required aria-required="true"
                               @isset($module)value="{{ $module->name }}"@endisset/>
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="text-center">
                        <input class="btn btn-primary" type="submit" value="{{ __('Submit') }}">
                        <a role="button" class="btn btn-secondary" href="{{ URL::previous() }}">{{ __('Cancel') }}</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

webapp/resources/views/modules/index.blade.php
@php
    /**
     *  Copyright 2020 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@php /** @var \App\TeachingModule[]|Illuminate\Pagination\LengthAwarePaginator $modules */ @endphp

@section('title', 'Modules')

@section('content')
        <div class="row justify-content-center">
            <div class="col-md-8">
                @can('create', \App\TeachingModule::class)
                    <a role="button" class="btn btn-primary" href="{{ route('modules.create') }}">Create Module</a>
                @endcan

                @if($modules->count() > 0)
                    <div class="list-group mt-4">
                        @foreach($modules as $module)
                            <a class="list-group-item list-group-item-action text-primary"
                               href="{{ route('modules.show', $module->id) }}">{{ $module->name }}</a>
                        @endforeach
                    </div>
                    {{ $modules->links() }}
                @else
                    <div class="alert alert-warning mt-2" role="alert">
                        {{ __('No modules have been created yet, or you are not part of any modules.') }}
                    </div>
                @endif
            </div>
        </div>
@endsection

webapp/resources/views/modules/show.blade.php
@php
    /**
     *  Copyright 2020 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@php /** @var \App\TeachingModule $module */ @endphp
@php /** @var \App\TeachingModule $moduleUser */ @endphp
@php /** @var \Spatie\Permission\Models\Role $activeRole */ @endphp
@php /** @var \Illuminate\Database\Eloquent\Collection $items */ @endphp
@php /** @var boolean $isAdmin */ @endphp

@section('title')Module {{ $module->name }}@endsection

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h2>{{ $module->name }}</h2>

            <div class="btn-toolbar" role="toolbar" aria-label="{{ __('Module users toolbar') }}">
                @if ($moduleUser and ($moduleUser->roles()->count() > 1 || $isAdmin))
                    <form method="POST" class="form-inline" action="{{ route('modules.switchRole', $module->id) }}">
                        @csrf
                        <div class="btn-group mr-2" role="group" aria-label="{{ __('Role switcher') }}">
                            @foreach ($moduleUser->roles()->get() as $role)
                                <button type="submit" name="role" value="{{ $role->id }}"
                                        class="btn btn-outline-success @if ($activeRole && $role->id == $activeRole->id) active @endif">
                                    {{ \App\Policies\TeachingModuleUserPolicy::cleanRoleName($role->name) }}
                                </button>
                            @endforeach
                            @if($isAdmin)
                                <button type="submit" name="role" value="unset"
                                        class="btn btn-outline-success @if (is_null($activeRole)) active @endif">
                                    {{ __('Admin') }}
                                </button>
                            @endif
                        </div>
                    </form>
                @endif
                @can('viewUsers', $module)
                    <div class="btn-group mr-2" role="group">
                        <a href="{{ route('modules.users.index', $module->id) }}"
                           class="btn btn-primary">{{ __('Users') }}</a>
                    </div>
                @endcan
                @can('update', $module)
                    <div class="btn-group mr-2" role="group">
                        <a href="{{ route('modules.edit', $module->id) }}" class="btn btn-primary">{{ __('Edit') }}</a>
                    </div>
                @endcan
                @can('delete', $module)
                    <div class="btn-group mr-2" role="group">
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
                            {{ __('Delete') }}
                        </button>
                    </div>
                    <x-modal-confirm :id="'deleteModal'" :title="__('Delete module?')">
                        <x-slot name="body">
                            {{ __('Do you want to delete Module #:id and all its enrolments and submissions?', ['id' => $module->id]) }}
                        </x-slot>
                        <form class="form-inline custom-control-inline mr-0"
                              action="{{ route('modules.destroy', $module->id) }}"
                              method="POST">
                            @csrf
                            @method('DELETE')
                            <input class="btn btn-danger" type="submit" value="{{ __('Delete') }}"/>
                        </form>
                    </x-modal-confirm>
                @endcan
            </div>
        </div>
    </div>
    <div class="row justify-content-center mt-4">
        <div class="col-md-12">
            <h3>Module content</h3>
            <div class="btn-toolbar" role="toolbar" aria-label="{{ __('Module items toolbar') }}">
                @can('createItem', $module)
                <a class="btn btn-primary mr-2"
                   href="{{ route('modules.items.create', $module->id) }}">{{ __('Create Item') }}</a>
                <a class="btn btn-primary mr-2"
                   href="{{ route('modules.items.create', ['module' => $module->id, 'type' => 'folder']) }}">{{ __('Create Folder') }}</a>
                <a class="btn btn-primary"
                   href="{{ route('modules.items.create', ['module' => $module->id, 'type' => 'assessment']) }}">{{ __('Create Assessment') }}</a>
                @endcan
            </div>
            <x-teaching-module-item-list :items="$items"/>
        </div>
    </div>
@endsection