webapp/routes/web.php
<?php
/**
 *  Copyright 2020-2021 Aston University
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false, 'reset' => false, 'password.request' => false]);

Route::get('/', 'HomeController@index')->name('home');

// COLOR PREFERENCES

Route::post('/theme/toggle', 'ThemeController@toggle')->name('theme.toggle');

// TOKEN MANAGEMENT

Route::get('/tokens', 'Auth\TokenManagementController@show')->name('tokens.show');
Route::delete('/tokens/{token}', 'Auth\TokenManagementController@destroy')->name('tokens.destroy');

// ADMIN MODE

Route::get('/admin/enable', 'AdminController@enable');
Route::post('/admin/enable', 'AdminController@enable')->name('enableAdmin');
Route::get('/admin/disable', 'AdminController@disable');
Route::post('/admin/disable', 'AdminController@disable')->name('disableAdmin');

// JOBS

Route::resource('jobs', 'JobController')->only([
    'index', 'show', 'destroy', 'store', 'create'
]);

Route::get('/jobs/{job}/results/{source}/{path}', 'JobController@showResult')
    ->name('jobs.showResult')
    ->where('path', '.*');

Route::get('/jobs/{job}/download', 'JobController@download')
    ->name('jobs.download');

Route::delete('/jobs', 'JobController@destroyMany')
    ->name('jobs.destroyMany');

// MODULES

Route::resource('modules', 'TeachingModuleController');

Route::post('/modules/{module}/switchRole', 'TeachingModuleController@switchRole')
    ->name('modules.switchRole');

Route::get('/modules/{module}/users/autocomplete', 'TeachingModuleUserController@autocomplete')
    ->name('modules.users.autocomplete');

Route::delete('/modules/{module}/users', 'TeachingModuleUserController@destroyMany')
    ->name('modules.users.destroyMany');

Route::get('/modules/{module}/users/import', 'TeachingModuleUserController@importForm')
    ->name('modules.users.importForm');
Route::post('/modules/{module}/users/import', 'TeachingModuleUserController@import')
    ->name('modules.users.import');

Route::resource('modules.users', 'TeachingModuleUserController');

Route::resource('modules.items', 'TeachingModuleItemController')->except(['index']);

Route::get(
    '/modules/{module}/items/{item}/copy',
    'TeachingModuleItemController@copyForm'
)->name('modules.items.copyForm');

Route::post(
    '/modules/{module}/items/{item}/copy',
    'TeachingModuleItemController@copy'
)->name('modules.items.copy');

// MODEL SOLUTION

Route::get(
    '/modules/{module}/assessments/{assessment}/solution',
    'AssessmentController@showModelSolution'
)->name('modules.assessments.showModelSolution');

Route::post(
    '/modules/{module}/assessments/{assessment}/solution',
    'AssessmentController@storeModelSolution'
)->name('modules.assessments.storeModelSolution');

Route::delete(
    '/modules/{module}/assessments/{assessment}/solution',
    'AssessmentController@destroyModelSolution'
)->name('modules.assessments.destroyModelSolution');

// FILE OVERRIDES

Route::get(
    '/modules/{module}/assessments/{assessment}/overrides',
    'AssessmentController@showOverrides'
)->name('modules.assessments.showOverrides');

Route::post(
    '/modules/{module}/assessments/{assessment}/overrides',
    'AssessmentController@storeOverrides'
)->name('modules.assessments.storeOverrides');

// SUBMISSIONS TABLE

Route::get(
    '/modules/{module}/assessments/{assessment}/submissions',
    'AssessmentController@showSubmissions'
)->name('modules.assessments.showSubmissions');

Route::post(
    '/modules/{module}/assessments/{assessment}/submissions/rerun',
    'AssessmentController@rerunSubmissions'
)->name('modules.assessments.rerunSubmissions');

Route::get(
    '/modules/{module}/assessments/{assessment}/submissions/csv',
    'AssessmentController@downloadSubmissionsCSV'
)->name('modules.assessments.downloadSubmissionsCSV');

// SUBMISSIONS COMPARISON

Route::get(
    '/modules/{module}/assessments/{assessment}/submissions/compare',
    'AssessmentSubmissionComparisonController@showCSVForm'
)->name('modules.assessments.compare.showCSVForm');

Route::post(
    '/modules/{module}/assessments/{assessment}/submissions/compare',
    'AssessmentSubmissionComparisonController@processCSV'
)->name('modules.assessments.compare.processCSV');

// ASSESSMENT TESTS

Route::get(
    '/modules/{module}/assessments/{assessment}/tests',
    'AssessmentController@showTests'
)->name('modules.assessments.showTests');

Route::get(
    '/modules/{module}/assessments/{assessment}/tests/edit',
    'AssessmentController@editTests'
)->name('modules.assessments.editTests');

Route::post(
    '/modules/{module}/assessments/{assessment}/tests',
    'AssessmentController@storeTests'
)->name('modules.assessments.storeTests');

Route::get(
    '/modules/{module}/assessments/{assessment}/tests/yaml',
    'AssessmentController@exportTestsToYAML'
)->name('modules.assessments.exportTestsToYAML');

Route::get(
    '/modules/{module}/assessments/{assessment}/tests/yaml/import',
    'AssessmentController@showImportTestsFromYAML'
)->name('modules.assessments.showImportTestsFromYAML');

Route::post(
    '/modules/{module}/assessments/{assessment}/tests/yaml/import',
    'AssessmentController@importTestsFromYAML'
)->name('modules.assessments.importTestsFromYAML');

// PROGRESS CHART

Route::get(
    '/modules/{module}/assessments/{assessment}/progress/chart',
    'AssessmentController@viewProgressChart'
)->name('modules.assessments.viewProgressChart');

Route::get(
    '/modules/{module}/assessments/{assessment}/progress/stats',
    'AssessmentController@jsonProgressStats'
)->name('modules.assessments.jsonProgressChart');

Route::get(
    '/modules/{module}/assessments/{assessment}/progress/entries/{className}/{testName}/{status}',
    'AssessmentController@jsonClassTestStatus'
)->name('modules.assessments.jsonClassTestStatus');

// SINGLE SUBMISSION MANAGEMENT

Route::post(
    '/modules/{module}/assessments/{assessment}/storeSubmission',
    'AssessmentController@storeSubmission'
)->name('modules.assessments.storeSubmission');

Route::get(
    '/modules/{module}/submissions/{submission}',
    'AssessmentSubmissionController@show'
)->name('modules.submissions.show');

Route::post(
    '/modules/{module}/submissions/{submission}/rerun',
    'AssessmentSubmissionController@rerun'
)->name('modules.submissions.rerun');

Route::delete(
    '/modules/{module}/submissions/{submission}',
    'AssessmentSubmissionController@destroy'
)->name('modules.submissions.destroy');

// HELP PAGES

Route::view(
    '/help/markdown/conditionals',
    'help.markdown_conditionals'
)->name('help.markdown.conditionals');

webapp/app/User.php
<?php

/**
 *  Copyright 2020 Aston University
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use LdapRecord\Laravel\Auth\AuthenticatesWithLdap;
use LdapRecord\Laravel\Auth\LdapAuthenticatable;
use Spatie\Permission\Traits\HasRoles;

/**
 * @property int id Unique ID for the object.
 * @property string name Name of the user.
 * @property string email Email of the user.
 * @property string password Hash of the user password.
 * @property Carbon created_at Timestamp when the model was created.
 * @property Carbon updated_at Timestamp when the model was updated.
 * @property boolean disabled_login If true, this user cannot login via user/pass:
 *                                  it can only be used through Sanctum tokens.
 *
 * @property Collection tokens Personal access tokens managed by Laravel Sanctum.
 *
 * @property string guid This is for storing your LDAP users objectguid. It is needed for locating and synchronizing
 * your LDAP user to the database.
 * @property string domain This is for storing your LDAP users connection name. It is needed for storing your
 * configured LDAP connection name of the user.
 */
class User extends Authenticatable implements LdapAuthenticatable
{
    use HasApiTokens;
    use HasFactory;
    use Notifiable;
    use AuthenticatesWithLdap;

    // Integrates the Spatie permissions management layer:
    // https://docs.spatie.be/laravel-permission/v3/basic-usage/basic-usage/
    use HasRoles;

    /**
     * @var string SUPER_ADMIN_ROLE Name of the role that is given all permissions by default.
     */
    const SUPER_ADMIN_ROLE = 'Super Admin';
    const ADMIN_MODE_ENABLED_KEY = 'admin_mode.enabled';

    /**
     * Needed to force spatie/laravel-permissions to go through the right guard, when LDAP auth is on.
     */
    protected $guard_name = 'web';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'guid', 'domain', 'disabled_login'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /** @var array Cache of enrolments for this users (depending on the module). */
    private $moduleUsers = [];

    /**
     * If the authenticated user has superuser privileges, this method enables / disables them for the session.
     * @param bool $enabled If TRUE, enables superuser privileges if available. Otherwise, disables them.
     */
    public static function setAdminMode(bool $enabled) {
        session([self::ADMIN_MODE_ENABLED_KEY => $enabled]);
    }

    /**
     * Returns TRUE iff admin mode is enabled in this session, FALSE otherwise.
     */
    public static function isAdminModeEnabled(): bool {
        return session(self::ADMIN_MODE_ENABLED_KEY, false);
    }

    /**
     * Returns TRUE iff this user can be considered to have all permissions by default.
     */
    public function isAdmin(): bool {
        return $this->hasRole(self::SUPER_ADMIN_ROLE) && self::isAdminModeEnabled();
    }

    /**
     * Returns a query that finds all the module users for this user.
     */
    public function moduleUsers() {
        return TeachingModuleUser::where('user_id', $this->id);
    }

    /**
     * Returns the teaching module user for this user in the specified module, if any.
     * We keep it stored between multiple calls, to reduce the number of DB queries.
     *
     * @param TeachingModule $module
     * @return TeachingModuleUser|null
     */
    public function moduleUser(TeachingModule $module) {
        if (!array_key_exists($module->id, $this->moduleUsers)) {
            /** @var TeachingModuleUser $moduleUser */
            $moduleUser = $module->users()->where('user_id', $this->id)->first();
            $this->moduleUsers[$module->id] = $moduleUser;
            return $moduleUser;
        }
        return $this->moduleUsers[$module->id];
    }

    /**
     * Returns an array with a list of all the locations where the user may be able to create an item
     * (roots of modules, and folders). Each array item has three keys: "module" (a reference to the
     * TeachingModule), "item" (a reference to the TeachingModuleItem), and "path" (a human-readable
     * representation of the path).
     */
    public function editableFolders(): array
    {
        /** @var TeachingModuleUser[] $moduleUsers */
        $moduleUsers = $this->moduleUsers()->with('module')->get()->sortBy('module.title');

        $folders = [];
        foreach ($moduleUsers as $moduleUser) {
            if ($this->can('createItem', $moduleUser->module)) {
                $path = '/' . $moduleUser->module->name;
                $folders[] = [
                    'module' => $moduleUser->module,
                    'item' => null,
                    'path' => $path,
                ];

                $this->_addChildrenFolders($moduleUser->module,
                    $path, $moduleUser->module->childFolders()->without('module')->get()->sortBy('title'),
                    $folders);
            }
        }

        return $folders;
    }

    /**
     * @param TeachingModule $module
     * @param string $basePath
     * @param TeachingModuleItem[]|Collection $childFolders
     * @param array $folders
     */
    private function _addChildrenFolders(TeachingModule $module, string $basePath, Collection $childFolders, array &$folders) {
        foreach ($childFolders as $child) {
            $path = $basePath . '/' . $child->title;
            $folders[] = [
                'module' => $module,
                'item' => $child,
                'path' => $path
            ];

            /** @var Folder $folder */
            $folder = $child->content;

            $this->_addChildrenFolders($module, $path,
                $folder->childFolders()->without('module')->orderBy('title')->get(),
                $folders);
        }
    }
}

webapp/resources/views/modules/users/_userBreadcrumb.blade.php
@php
    /**
     *  Copyright 2020 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp
<div class="row justify-content-center">
    <div class="col-md-8">
        <x-item-path :module="$module">
            @can('viewUsers', $module)
                <li class="breadcrumb-item"><a href="{{ route('modules.users.index', ['module' => $module->id]) }}">{{ __('Users') }}</a></li>
            @else
                <li class="breadcrumb-item">{{ __('Users') }}</li>
            @endcan
            <li class="breadcrumb-item active">{{ $text }}</li>
        </x-item-path>
    </div>
</div>

webapp/resources/views/modules/users/create.blade.php
@php
    /**
     *  Copyright 2020 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@section('title')
    {{ __('Enrol User') }}
@endsection

@section('content')
    @include('modules.users._userBreadcrumb', ['text' => __('Enrol User')])

    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" action="{{ route('modules.users.store', $module->id) }}">
                @csrf

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="email">{{ __('Email') }}</label>
                    <div class="col-sm-10">
                        <input type="email" required aria-required="true"
                               class="af-autocomplete-email form-control @error('email') is-invalid @enderror"
                               id="email"
                               name="email"
                               placeholder="{{ __('email address (prefix autocomplete based on registered users)') }}"
                               value="{{ old('email') }}"
                        />
                        @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>

                @include('modules.users._roleSelector')

                <div class="text-center">
                    <input class="btn btn-primary" type="submit" value="{{ __('Submit') }}">
                    <a role="button" class="btn btn-secondary"
                       href="{{ route('modules.users.index', $module->id) }}">{{ __('Cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('extrajs')
    <script type="application/javascript">
        $('.af-autocomplete-email').autocomplete({
            delay: 300,
            source: (request, callback) => {
                axios.get("{{ route('modules.users.autocomplete', $module->id) }}", {
                    params: {prefix: request.term}
                }).then(function (response) {
                    callback(response.data);
                });
            }
        });
    </script>
@endsection

webapp/resources/views/modules/users/edit.blade.php
@php
    /**
     *  Copyright 2020 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@section('title')
    {{ __('Edit User') }}
@endsection

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <x-item-path :module="$module">
                @can('viewUsers', $module)
                    <li class="breadcrumb-item"><a href="{{ route('modules.users.index', ['module' => $module->id]) }}">{{ __('Users') }}</a></li>
                @else
                    <li class="breadcrumb-item">{{ __('Users') }}</li>
                @endcan
                @can('view', $moduleUser)
                    <li class="breadcrumb-item"><a href="{{ route('modules.users.show', ['module' => $module->id, 'user' => $moduleUser->id]) }}">{{ $moduleUser->user->name }}</a></li>
                @else
                    <li class="breadcrumb-item">{{ $moduleUser->user->name }}</li>
                @endcan
                <li class="breadcrumb-item active">{{ __('Edit User') }}</li>
            </x-item-path>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST"
                  action="{{ route('modules.users.update', ['module' => $module->id, 'user' => $moduleUser->id]) }}">
                @csrf
                @method('PUT')
                @include('modules.users._roleSelector')

                <div class="text-center">
                    <input class="btn btn-primary" type="submit" value="{{ __('Submit') }}">
                    <a role="button" class="btn btn-secondary"
                       href="{{ route('modules.users.show', ['module' => $module->id, 'user' => $moduleUser->id]) }}">{{ __('Cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
@endsection

webapp/resources/views/modules/users/index.blade.php
@php
    /**
     *  Copyright 2020-2021 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@php /** @var \App\TeachingModule|Illuminate\Pagination\LengthAwarePaginator $module */ @endphp
@php /** @var \App\TeachingModuleUser[]|Illuminate\Pagination\LengthAwarePaginator $users */ @endphp

@section('title', 'Users in ' . $module->name)

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <x-item-path :module="$module">
                <li class="breadcrumb-item active">{{ __('Users') }}</li>
            </x-item-path>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div>
                @can('enrolUsers', $module)
                    <a class="btn btn-primary"
                       href="{{ route('modules.users.importForm', $module->id) }}">{{ __('Import Users') }}</a>
                    <a class="btn btn-primary"
                       href="{{ route('modules.users.create', $module->id) }}">{{ __('Enrol User') }}</a>
                @endcan
                @can('removeUsers', $module)
                    <button id="deleteManyModalButton" type="button" class="btn btn-danger" data-toggle="modal"
                            data-target="#deleteManyModal" data-af-row-select-table="#usersTable">
                        {{ __('Remove selected') }}
                    </button>

                    <x-modal-confirm :id="'deleteManyModal'" :title="__('Remove checked users from the module?')">
                        <x-slot name="body">
                            {{ __('Do you wish to remove the checked users from the module? This will also delete their submissions.') }}
                        </x-slot>
                        <form class="form-inline custom-control-inline mr-0"
                              action="{{ route('modules.users.destroyMany', $module->id) }}"
                              method="POST" id="deleteManyForm">
                            @csrf
                            @method('DELETE')
                            <input class="btn btn-danger" type="submit" value="{{ __('Remove') }}"/>
                        </form>
                    </x-modal-confirm>
                @endcan
                <a class="btn btn-secondary" href="{{ route('modules.show', $module->id ) }}">{{ __('Back') }}</a>
            </div>

            @if($users->count() > 0)
                <p class="mt-4">
                    {{ __('This is the list of users enrolled to :moduleName. To view the details of a user and edit their roles, click on their name.', ['moduleName' => $module->name ]) }}
                </p>
                <table class="table table-hover mt-4 af-row-select-table" id="usersTable">
                    <thead>
                    <th scope="col"><input type="checkbox" class="af-row-select-all"/></th>
                    <th scope="col">{{ __('Name') }}</th>
                    <th scope="email">{{ __('Email') }}</th>
                    <th scope="col">{{ __('Roles') }}</th>
                    </thead>
                    <tbody>
                    @foreach ($users as $u)
                        <tr>
                            <td><input type="checkbox" class="af-row-select" value="{{ $u->id }}"/></td>
                            <td>
                                <a href="{{ route('modules.users.show', ['module' => $module->id, 'user' => $u->id])  }}">{{ $u->user->name }}</a>
                            </td>
                            <td><a href="mailto:{{ $u->user->email }}">{{ $u->user->email  }}</a></td>
                            <td>{{ implode(', ', $u->getCleanRoleNames()) }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $users->links() }}
            @else
                <div class="alert alert-warning mt-2" role="alert">
                    {{ __('No users have been assigned yet to this module.') }}
                </div>
            @endif
        </div>
    </div>
@endsection

@section('extrajs')
    <script type="application/javascript">
        $('#deleteManyForm').on('submit', () => {
            $('#usersTable input.af-row-select:checked').each((i, e) => {
                $('<input type="hidden">').attr({
                    name: 'ids[]',
                    value: e.value
                }).appendTo('#deleteManyForm');
            });
            return true;
        });
    </script>
@endsection

webapp/resources/views/modules/users/show.blade.php
@php
    /**
     *  Copyright 2020-2021 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@php
/**
 * @var \App\TeachingModule $module
 * @var \App\TeachingModuleUser $moduleUser
 * @var \App\Http\Controllers\SubmissionsTable $submissions
 */
@endphp

@section('title'){{ __(':name in :module', ['module' => $module->name, 'name' => $moduleUser->user->name ]) }}@endsection

@section('content')
    @include('modules.users._userBreadcrumb', ['text' => $moduleUser->user->name ])

    <div class="row justify-content-center">
        <div class="col-md-12">
            <h2>{{ __('User details') }}</h2>

            <div>
                @can('update', $moduleUser)
                    <a href="{{ route('modules.users.edit', ['module' => $module->id, 'user' => $moduleUser->id]) }}"
                       class="btn btn-primary">{{ __('Edit roles') }}</a>
                @endcan
                @can('delete', $moduleUser)
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
                        {{ __('Remove') }}
                    </button>
                    <x-modal-confirm :id="'deleteModal'" :title="__('Remove User from Module?')">
                        <x-slot name="body">
                            {{ __('Do you want to remove :name from the module? This will delete all associated submissions.', ['name' => $moduleUser->user->name ]) }}
                        </x-slot>
                        <form class="form-inline custom-control-inline mr-0"
                              action="{{ route('modules.users.destroy', ['module' => $module->id, 'user' => $moduleUser->id]) }}"
                              method="POST">
                            @csrf
                            @method('DELETE')
                            <input class="btn btn-danger" type="submit" value="{{ __('Remove') }}"/>
                        </form>
                    </x-modal-confirm>
                @endcan
                <a href="{{ URL::previous() }}" class="btn btn-secondary">{{ __('Back') }}</a>
            </div>

            <table class="table mt-4">
                <tbody>
                <tr>
                    <th scope="row">{{ __('Email') }}</th>
                    <td><a href="mailto:{{ $moduleUser->user->email }}">{{ $moduleUser->user->email }}</a></td>
                </tr>
                <tr>
                    <th scope="row">{{ __('Roles') }}</th>
                    <td>{{ implode(', ', $moduleUser->getCleanRoleNames()) }}
                </tr>
                <tr>
                    <th scope="row">{{ __('Enrolled at') }}</th>
                    <td>{{ $moduleUser->created_at }}
                </tr>
                </tbody>
            </table>

            @if(!is_null($submissions))
                @if($submissions->submissions->isEmpty())
                    <div class="alert alert-warning mt-2" role="alert">
                        {{ __('This user has not made any submissions in this module yet.') }}
                    </div>
                @else
                    <h3>
                        {{ __('Submissions') }}
                    </h3>
                    <div class="btn-toolbar mb-2" role="toolbar" aria-label="Folder items toolbar">
                        <a href="{{ route('modules.users.show', ['module' => $module->id, 'user' => $moduleUser->id, \App\Http\Controllers\SubmissionsTable::SHOW_LATEST_KEY => !$submissions->showLatest ]) }}"
                           class="btn btn-primary mr-2">{{ $submissions->showLatest ? __('Show all attempts') : __('Show last attempts') }}</a>
                    </div>

                    @include('components.submissions-table', ['table' => $submissions])
                @endif
            @endif
        </div>
    </div>
@endsection