webapp/routes/web.php
<?php
/**
 *  Copyright 2020-2021 Aston University
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false, 'reset' => false, 'password.request' => false]);

Route::get('/', 'HomeController@index')->name('home');

// COLOR PREFERENCES

Route::post('/theme/toggle', 'ThemeController@toggle')->name('theme.toggle');

// TOKEN MANAGEMENT

Route::get('/tokens', 'Auth\TokenManagementController@show')->name('tokens.show');
Route::delete('/tokens/{token}', 'Auth\TokenManagementController@destroy')->name('tokens.destroy');

// ADMIN MODE

Route::get('/admin/enable', 'AdminController@enable');
Route::post('/admin/enable', 'AdminController@enable')->name('enableAdmin');
Route::get('/admin/disable', 'AdminController@disable');
Route::post('/admin/disable', 'AdminController@disable')->name('disableAdmin');

// JOBS

Route::resource('jobs', 'JobController')->only([
    'index', 'show', 'destroy', 'store', 'create'
]);

Route::get('/jobs/{job}/results/{source}/{path}', 'JobController@showResult')
    ->name('jobs.showResult')
    ->where('path', '.*');

Route::get('/jobs/{job}/download', 'JobController@download')
    ->name('jobs.download');

Route::delete('/jobs', 'JobController@destroyMany')
    ->name('jobs.destroyMany');

// MODULES

Route::resource('modules', 'TeachingModuleController');

Route::post('/modules/{module}/switchRole', 'TeachingModuleController@switchRole')
    ->name('modules.switchRole');

Route::get('/modules/{module}/users/autocomplete', 'TeachingModuleUserController@autocomplete')
    ->name('modules.users.autocomplete');

Route::delete('/modules/{module}/users', 'TeachingModuleUserController@destroyMany')
    ->name('modules.users.destroyMany');

Route::get('/modules/{module}/users/import', 'TeachingModuleUserController@importForm')
    ->name('modules.users.importForm');
Route::post('/modules/{module}/users/import', 'TeachingModuleUserController@import')
    ->name('modules.users.import');

Route::resource('modules.users', 'TeachingModuleUserController');

Route::resource('modules.items', 'TeachingModuleItemController')->except(['index']);

Route::get(
    '/modules/{module}/items/{item}/copy',
    'TeachingModuleItemController@copyForm'
)->name('modules.items.copyForm');

Route::post(
    '/modules/{module}/items/{item}/copy',
    'TeachingModuleItemController@copy'
)->name('modules.items.copy');

// MODEL SOLUTION

Route::get(
    '/modules/{module}/assessments/{assessment}/solution',
    'AssessmentController@showModelSolution'
)->name('modules.assessments.showModelSolution');

Route::post(
    '/modules/{module}/assessments/{assessment}/solution',
    'AssessmentController@storeModelSolution'
)->name('modules.assessments.storeModelSolution');

Route::delete(
    '/modules/{module}/assessments/{assessment}/solution',
    'AssessmentController@destroyModelSolution'
)->name('modules.assessments.destroyModelSolution');

// FILE OVERRIDES

Route::get(
    '/modules/{module}/assessments/{assessment}/overrides',
    'AssessmentController@showOverrides'
)->name('modules.assessments.showOverrides');

Route::post(
    '/modules/{module}/assessments/{assessment}/overrides',
    'AssessmentController@storeOverrides'
)->name('modules.assessments.storeOverrides');

// SUBMISSIONS TABLE

Route::get(
    '/modules/{module}/assessments/{assessment}/submissions',
    'AssessmentController@showSubmissions'
)->name('modules.assessments.showSubmissions');

Route::post(
    '/modules/{module}/assessments/{assessment}/submissions/rerun',
    'AssessmentController@rerunSubmissions'
)->name('modules.assessments.rerunSubmissions');

Route::get(
    '/modules/{module}/assessments/{assessment}/submissions/csv',
    'AssessmentController@downloadSubmissionsCSV'
)->name('modules.assessments.downloadSubmissionsCSV');

// SUBMISSIONS COMPARISON

Route::get(
    '/modules/{module}/assessments/{assessment}/submissions/compare',
    'AssessmentSubmissionComparisonController@showCSVForm'
)->name('modules.assessments.compare.showCSVForm');

Route::post(
    '/modules/{module}/assessments/{assessment}/submissions/compare',
    'AssessmentSubmissionComparisonController@processCSV'
)->name('modules.assessments.compare.processCSV');

// ASSESSMENT TESTS

Route::get(
    '/modules/{module}/assessments/{assessment}/tests',
    'AssessmentController@showTests'
)->name('modules.assessments.showTests');

Route::get(
    '/modules/{module}/assessments/{assessment}/tests/edit',
    'AssessmentController@editTests'
)->name('modules.assessments.editTests');

Route::post(
    '/modules/{module}/assessments/{assessment}/tests',
    'AssessmentController@storeTests'
)->name('modules.assessments.storeTests');

Route::get(
    '/modules/{module}/assessments/{assessment}/tests/yaml',
    'AssessmentController@exportTestsToYAML'
)->name('modules.assessments.exportTestsToYAML');

Route::get(
    '/modules/{module}/assessments/{assessment}/tests/yaml/import',
    'AssessmentController@showImportTestsFromYAML'
)->name('modules.assessments.showImportTestsFromYAML');

Route::post(
    '/modules/{module}/assessments/{assessment}/tests/yaml/import',
    'AssessmentController@importTestsFromYAML'
)->name('modules.assessments.importTestsFromYAML');

// PROGRESS CHART

Route::get(
    '/modules/{module}/assessments/{assessment}/progress/chart',
    'AssessmentController@viewProgressChart'
)->name('modules.assessments.viewProgressChart');

Route::get(
    '/modules/{module}/assessments/{assessment}/progress/stats',
    'AssessmentController@jsonProgressStats'
)->name('modules.assessments.jsonProgressChart');

Route::get(
    '/modules/{module}/assessments/{assessment}/progress/entries/{className}/{testName}/{status}',
    'AssessmentController@jsonClassTestStatus'
)->name('modules.assessments.jsonClassTestStatus');

// SINGLE SUBMISSION MANAGEMENT

Route::post(
    '/modules/{module}/assessments/{assessment}/storeSubmission',
    'AssessmentController@storeSubmission'
)->name('modules.assessments.storeSubmission');

Route::get(
    '/modules/{module}/submissions/{submission}',
    'AssessmentSubmissionController@show'
)->name('modules.submissions.show');

Route::post(
    '/modules/{module}/submissions/{submission}/rerun',
    'AssessmentSubmissionController@rerun'
)->name('modules.submissions.rerun');

Route::delete(
    '/modules/{module}/submissions/{submission}',
    'AssessmentSubmissionController@destroy'
)->name('modules.submissions.destroy');

// HELP PAGES

Route::view(
    '/help/markdown/conditionals',
    'help.markdown_conditionals'
)->name('help.markdown.conditionals');

webapp/resources/views/modules/items/_createEditAssessment.blade.php
@php
    /**
     *  Copyright 2020-2021 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */

    /**
     * @var App\TeachingModuleItem $item
     * @var App\TeachingModule $module
     * @var App\Assessment $assessment
     * @var ?App\AssessmentSubmission $submission
     */
@endphp
<h3 class="mt-4 text-center">{{ __('Assessment details') }}</h3>
<div class="form-group row form-inline">
    <label for="dueBy" class="col-sm-3">{{ __('Submission due by') }}</label>
    <div class="input-append date form_datetime col-sm-6">
        <span class="add-on">
            <div class="input-group @error('dueBy') is-invalid @endif">
                <input size="16" class="form-control @error('dueBy') is-invalid @endif"
                    type="text" name="dueBy"
                    value="{{ old('dueBy', $item->content && $item->content->due_by ? $item->content->due_by->format($dateTimeFormat) : '') }}"
                    readonly />
                <div class="input-group-append">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
            @error('dueBy')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </span>
    </div>
</div>

webapp/resources/views/modules/items/copy.blade.php
@php
    /**
     *  Copyright 2022 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@php /** @var \App\TeachingModuleItem $item */ @endphp

@section('title')
    {{ __('Copy Item')}}
@endsection

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <x-item-path :module="$module" :item="$item">
                <li class="breadcrumb-item active">{{ __('Copy Item') }}</li>
            </x-item-path>

            <form method="POST"
                  action="{{ route('modules.items.copy', ['module' => $module, 'item' => $item ]) }}">
                @csrf

                <div class="form-group row">
                    <label for="targetPath">{{ __('Target path') }}</label>
                    <select name="targetPath" id="targetPath" class="form-control">
                        @foreach ($targetFolders as $target)
                        <option value="{{ $target['module']->id . '|' . ($target['item'] ? $target['item']->id : '') }}">{{ $target['path'] }}</option>
                        @endforeach
                    </select>
                    @error('targetPath')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>

                <div class="text-center">
                    <input class="btn btn-primary" type="submit" value="{{ __('Submit') }}">
                    <a role="button" class="btn btn-secondary"
                       @if($folder) href="{{ route('modules.items.show', ['module' => $module, 'item' => $container]) }}"
                       @else href="{{ route('modules.show', $module->id) }}" @endif
                    >{{ __('Cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
@endsection

webapp/resources/views/modules/items/create.blade.php
@php
    /**
     *  Copyright 2020-2021 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@php /** @var \App\TeachingModuleItem $item */ @endphp

@section('title')
    @if($item->exists){{ __('Edit Item') }}@else{{ __('Create Item')}}@endisset
@endsection

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if($item->exists)
                <x-item-path :module="$module" :item="$item">
                    <li class="breadcrumb-item active">{{ __('Edit') }}</li>
                </x-item-path>
            @else
                <x-item-path :module="$module" :item="$container">
                    <li class="breadcrumb-item active">{{ __($itemType === 'folder' ? 'Create Folder' : ($itemType === 'assessment' ? 'Create Assessment' : 'Create Item')) }}</li>
                </x-item-path>
            @endif

            <form method="POST"
                  @if($item->exists) action="{{ route('modules.items.update', ['module' => $module->id, 'item' => $item->id]) }}"
                  @else action="{{ route('modules.items.store', $module->id) }}" @endif>
                @csrf
                @if($item->exists)
                    @method('PUT')
                @else
                    @if(isset($itemType) && ($itemType === 'folder' || $itemType === "assessment" ))
                        <input type="hidden" name="itemType" value="{{ $itemType }}"/>
                    @endif
                    @if(isset($folder) && $folder)
                        <input type="hidden" name="itemFolder" value="{{ $folder }}" />
                    @endif
                @endif

                <div class="form-group row">
                    <label for="itemTitle">{{ __('Title') }}</label>
                    <input type="text" class="form-control @error('title') is-invalid @enderror" id="itemTitle"
                           name="itemTitle" required aria-required="true"
                           value="{{ old('itemTitle', $item->title) }}"/>
                    @error('itemTitle')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>

                <div class="form-group row">
                    <label for="itemDescription">{{ __('Markdown description') }} (<x-markdown-help-links/>)</label>
                    <textarea class="form-control @error('itemDescription') is-invalid @endif" id="itemDescription"
                              rows="10" required aria-required="true"
                              name="itemDescription">{{ old('itemDescription', $item->description_markdown) }}</textarea>
                    @error('itemDescription')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>

                <div class="form-group row">
                    <div class="form-check">
                        <input class="form-check-input @error('itemAvailable') is-invalid @endif" type="checkbox"
                               id="itemAvailable" name="itemAvailable"
                               @if(old('itemAvailable', $item->available)) checked @endif />
                        <label class="form-check-label"
                               for="itemAvailable">{{ __('Make available to students?') }}</label>
                        @error('itemAvailable')
                        <div class="invalid-feedback">
                            <strong>{{ $message }}</strong>
                        </div>
                        @enderror
                    </div>
                </div>

                <div class="form-group row form-inline">
                    <label for="itemAvailableStart" class="col-sm-3 text-left">{{ __('Available from') }}</label>
                    <div class="input-append date form_datetime col-sm-6">
                        <span class="add-on">
                            <div class="input-group @error('itemAvailableStart') is-invalid @endif">
                                <input size="16" class="form-control @error('itemAvailableStart') is-invalid @endif"
                                       type="text" name="itemAvailableStart"
                                       value="{{ old('itemAvailableStart', $item->available_from ? $item->available_from->format($dateTimeFormat) : '') }}"
                                       readonly/>
                                <div class="input-group-append">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                            @error('itemAvailableStart')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </span>
                    </div>
                </div>

                <div class="form-group row form-inline">
                    <label for="itemAvailableEnd" class="col-sm-3">{{ __('Available until') }}</label>
                    <div class="input-append date form_datetime col-sm-6">
                        <span class="add-on">
                            <div class="input-group @error('itemAvailableEnd') is-invalid @endif">
                                <input size="16" class="form-control @error('itemAvailableEnd') is-invalid @endif"
                                       type="text" name="itemAvailableEnd"
                                       value="{{ old('itemAvailableEnd', $item->available_until ? $item->available_until->format($dateTimeFormat) : '') }}"
                                       readonly/>
                                <div class="input-group-append">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                            @error('itemAvailableEnd')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </span>
                    </div>
                </div>

                @if($itemType == 'assessment')
                    @include('modules.items._createEditAssessment')
                @endif

                <div class="text-center">
                    <input class="btn btn-primary" type="submit" value="{{ __('Submit') }}">
                    <a role="button" class="btn btn-secondary"
                       @if(isset($folder) && $folder) href="{{ route('modules.items.show', ['module' => $module->id, 'item' => $container->id]) }}"
                       @else href="{{ route('modules.show', $module->id) }}" @endif
                    >{{ __('Cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('extrajs')
    <script>
        $('.form_datetime').datetimepicker({
            format: "dd/mm/yyyy hh:ii",
            weekStart: 1,
            clearBtn: true,
            autoclose: true,
            todayBtn: true,
            pickerPosition: "bottom-left",
        });
    </script>
@endsection

webapp/resources/views/modules/items/listItem.blade.php
@php
    /**
     *  Copyright 2020 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp
@php /** @var App\TeachingModuleItem $item */ @endphp

<div class="list-group-item list-group-item-action @unless($item->isDirectlyAvailable()) list-group-item-secondary @endif">
    <div class="d-flex w-100 justify-content-between">
        <h4>
            @unless($item->available)
                <span class="fa fa-eye-slash"
                      title="{{ __('Item unavailable to students') }}"></span>
            @endunless
            @if($item->content_id)
                <span class="fa {{ $item->content->getIcon() }}"></span>
                <a href="{{ route('modules.items.show', ['module' => $item->teaching_module_id, 'item' => $item->id]) }}">{{ $item->title }}</a>
            @else
                {{ $item->title }}
            @endif
        </h4>
        <div class="btn-group">
            @can('update', $item)
                <a class="btn btn-primary"
                   href="{{ route('modules.items.edit', ['module' => $item->teaching_module_id, 'item' => $item->id]) }}">{{ __('Edit') }}</a>
            @endcan
            @can('copy', $item)
                <a class="btn btn-primary"
                   href="{{ route('modules.items.copyForm', ['module' => $item->teaching_module_id, 'item' => $item->id]) }}">{{ __('Copy') }}</a>
            @endcan
            @can('delete', $item)
                <button type="button" class="btn btn-danger" data-toggle="modal"
                        data-target="#deleteItemModal{{ $item->id }}">{{ __('Delete') }}</button>
            @endcan
        </div>
    </div>
    <span class="mb-0">@markdown($item->description_markdown)</span>
    @if($item->available_from and $item->available_until)
        <div><small
                class="text-muted">{{ __('Available from :start until :end', ['start' => $item->available_from, 'end' => $item->available_until ]) }}</small>
        </div>
    @elseif($item->available_from)
        <div><small
                class="text-muted">{{ __('Available from :dateTime', ['dateTime' => $item->available_from]) }}</small>
        </div>
    @elseif($item->available_until)
        <div><small
                class="text-muted">{{ __('Available until :dateTime', ['dateTime' => $item->available_until]) }}</small>
        </div>
    @endif
    @if($item->getSimpleContentType() == 'assessment' && $item->content->due_by)
        <div><small class="text-muted">{{ __('Submission due by :dateTime', ['dateTime' => $item->content->due_by ]) }}</small></div>
    @endif
</div>
@can('delete', $item)
    <x-modal-confirm :id="'deleteItemModal' . $item->id" :title="__('Delete item?')">
        <x-slot
            name="body">{{ __('Do you want to delete Item #:id (:title)?', ['id' => $item->id, 'title' => $item->title]) }}</x-slot>
        <form class="form-inline custom-control-inline mr-0"
              action="{{ route('modules.items.destroy', ['module' => $item->teaching_module_id, 'item' => $item->id]) }}"
              method="POST">
            @csrf
            @method('DELETE')
            <input class="btn btn-danger" type="submit" value="{{ __('Delete') }}"/>
        </form>
    </x-modal-confirm>
@endcan

webapp/resources/views/modules/items/show.blade.php
@php
    /**
     *  Copyright 2020 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@php /** @var \App\TeachingModule $module */ @endphp
@php /** @var \App\TeachingModuleItem $item */ @endphp

@section('title'){{ $item->title }}@endsection

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <x-item-path :module="$module" :item="$item"/>

            @if ($item->content_type === \App\Folder::CONTENT_TYPE)
                @include('modules.items.showFolder', ['folder' => $item->content, 'children' => $item->content->childrenVisibleByUser()])
            @elseif ($item->content_type === 'App\Assessment')
                @include('modules.items.showAssessment', ['assessment' => $item->content])
            @endif
        </div>
    </div>
@endsection

webapp/resources/views/modules/items/showAssessment.blade.php
@php
    /**
     *  Copyright 2020 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */

    /**
     * @var App\TeachingModuleItem $item
     * @var App\TeachingModule $module
     * @var App\Assessment $assessment
     */
@endphp
<div class="btn-toolbar" role="toolbar" aria-label="{{ __('Folder items toolbar') }}">
    @can('viewModelSolution', $assessment)
        <a href="{{ route('modules.assessments.showModelSolution', ['module' => $module->id, 'assessment' => $assessment->id ]) }}"
           class="btn btn-primary mr-2">{{ __('Model solution') }}</a>
    @endcan
    @can('viewOverrides', $assessment)
        <a href="{{ route('modules.assessments.showOverrides', ['module' => $module->id, 'assessment' => $assessment->id]) }}"
           class="btn btn-primary mr-2">{{ __('File overrides') }}</a>
    @endcan
    @can('viewTests', $assessment)
        <a href="{{ route('modules.assessments.showTests', ['module' => $module->id, 'assessment' => $assessment->id]) }}"
           class="btn btn-primary mr-2">{{ __('Tests') }}</a>
    @endcan
    @can('viewProgress', $assessment)
        <a href="{{ route('modules.assessments.viewProgressChart', ['module' => $module->id, 'assessment' => $assessment->id]) }}"
           class="btn btn-primary mr-2" target="_blank">{{ __('Progress') }}</a>
    @endcan
    @can('viewSubmissions', $assessment)
       <a href="{{ route('modules.assessments.showSubmissions', ['module' => $module->id, 'assessment' => $assessment->id]) }}"
          class="btn btn-primary" target="_blank">{{ __('Submissions') }}</a>
    @endcan
</div>
@if($assessment->latestModelSolution)
    @php
        /**
         * @var App\TeachingModule $module
         * @var App\Assessment $assessment
         */
         $tmu = Auth::user()->moduleUser($module);
         $submission = $tmu ? $assessment->latestSubmissionFor($tmu)->first() : null;
    @endphp
    @if($tmu)
        @include('assessments._showSubmission', [ 'submission' => $submission, 'byClass' => false ])
        @include('assessments._uploadSubmission', [ 'submission' => $submission, 'keepLatest' => Config::get(\App\Assessment::CONFIG_KEEP_LATEST_ATTEMPTS) ])
        @include('assessments._rerunSubmission', [ 'submission' => $submission, 'keepLatest' => Config::get(\App\Assessment::CONFIG_KEEP_LATEST_ATTEMPTS) ])
        @include('assessments._deleteSubmission', [ 'submission' => $submission ])
    @else
        <div class="alert alert-warning mt-2" role="alert">{{ __('You are not enrolled in this module.') }}</div>
    @endif
@else
    <div class="alert alert-warning mt-2"
         role="alert">{{ __('The assessment has not been set up yet. Please check back in a while.') }}</div>
@endif

webapp/resources/views/modules/items/showFolder.blade.php
@php
    /**
     *  Copyright 2020 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */

/**
 * @var App\TeachingModuleItem $item
 * @var App\TeachingModule $module
 * @var App\Folder $folder
 * @var \Illuminate\Database\Eloquent\Collection $children
 */
@endphp

<div class="btn-toolbar" role="toolbar" aria-label="{{ __('Folder items toolbar') }}">
    @can('createItem', $module)
        <a class="btn btn-primary mr-2"
           href="{{ route('modules.items.create', ['module' => $module->id, 'folder' => $item->content->id]) }}">{{ __('Create Item') }}</a>
        <a class="btn btn-primary mr-2"
           href="{{ route('modules.items.create', ['module' => $module->id, 'type' => 'folder', 'folder' => $item->content->id]) }}">{{ __('Create Folder') }}</a>
        <a class="btn btn-primary mr-2"
           href="{{ route('modules.items.create', ['module' => $module->id, 'type' => 'assessment', 'folder' => $item->content->id]) }}">{{ __('Create Assessment') }}</a>
    @endcan
</div>

<x-teaching-module-item-list :items="$children"/>