webapp/routes/web.php
<?php
/**
 *  Copyright 2020-2021 Aston University
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false, 'reset' => false, 'password.request' => false]);

Route::get('/', 'HomeController@index')->name('home');

// COLOR PREFERENCES

Route::post('/theme/toggle', 'ThemeController@toggle')->name('theme.toggle');

// TOKEN MANAGEMENT

Route::get('/tokens', 'Auth\TokenManagementController@show')->name('tokens.show');
Route::delete('/tokens/{token}', 'Auth\TokenManagementController@destroy')->name('tokens.destroy');

// ADMIN MODE

Route::get('/admin/enable', 'AdminController@enable');
Route::post('/admin/enable', 'AdminController@enable')->name('enableAdmin');
Route::get('/admin/disable', 'AdminController@disable');
Route::post('/admin/disable', 'AdminController@disable')->name('disableAdmin');

// JOBS

Route::resource('jobs', 'JobController')->only([
    'index', 'show', 'destroy', 'store', 'create'
]);

Route::get('/jobs/{job}/results/{source}/{path}', 'JobController@showResult')
    ->name('jobs.showResult')
    ->where('path', '.*');

Route::get('/jobs/{job}/download', 'JobController@download')
    ->name('jobs.download');

Route::delete('/jobs', 'JobController@destroyMany')
    ->name('jobs.destroyMany');

// MODULES

Route::resource('modules', 'TeachingModuleController');

Route::post('/modules/{module}/switchRole', 'TeachingModuleController@switchRole')
    ->name('modules.switchRole');

Route::get('/modules/{module}/users/autocomplete', 'TeachingModuleUserController@autocomplete')
    ->name('modules.users.autocomplete');

Route::delete('/modules/{module}/users', 'TeachingModuleUserController@destroyMany')
    ->name('modules.users.destroyMany');

Route::get('/modules/{module}/users/import', 'TeachingModuleUserController@importForm')
    ->name('modules.users.importForm');
Route::post('/modules/{module}/users/import', 'TeachingModuleUserController@import')
    ->name('modules.users.import');

Route::resource('modules.users', 'TeachingModuleUserController');

Route::resource('modules.items', 'TeachingModuleItemController')->except(['index']);

Route::get(
    '/modules/{module}/items/{item}/copy',
    'TeachingModuleItemController@copyForm'
)->name('modules.items.copyForm');

Route::post(
    '/modules/{module}/items/{item}/copy',
    'TeachingModuleItemController@copy'
)->name('modules.items.copy');

// MODEL SOLUTION

Route::get(
    '/modules/{module}/assessments/{assessment}/solution',
    'AssessmentController@showModelSolution'
)->name('modules.assessments.showModelSolution');

Route::post(
    '/modules/{module}/assessments/{assessment}/solution',
    'AssessmentController@storeModelSolution'
)->name('modules.assessments.storeModelSolution');

Route::delete(
    '/modules/{module}/assessments/{assessment}/solution',
    'AssessmentController@destroyModelSolution'
)->name('modules.assessments.destroyModelSolution');

// FILE OVERRIDES

Route::get(
    '/modules/{module}/assessments/{assessment}/overrides',
    'AssessmentController@showOverrides'
)->name('modules.assessments.showOverrides');

Route::post(
    '/modules/{module}/assessments/{assessment}/overrides',
    'AssessmentController@storeOverrides'
)->name('modules.assessments.storeOverrides');

// SUBMISSIONS TABLE

Route::get(
    '/modules/{module}/assessments/{assessment}/submissions',
    'AssessmentController@showSubmissions'
)->name('modules.assessments.showSubmissions');

Route::post(
    '/modules/{module}/assessments/{assessment}/submissions/rerun',
    'AssessmentController@rerunSubmissions'
)->name('modules.assessments.rerunSubmissions');

Route::get(
    '/modules/{module}/assessments/{assessment}/submissions/csv',
    'AssessmentController@downloadSubmissionsCSV'
)->name('modules.assessments.downloadSubmissionsCSV');

// SUBMISSIONS COMPARISON

Route::get(
    '/modules/{module}/assessments/{assessment}/submissions/compare',
    'AssessmentSubmissionComparisonController@showCSVForm'
)->name('modules.assessments.compare.showCSVForm');

Route::post(
    '/modules/{module}/assessments/{assessment}/submissions/compare',
    'AssessmentSubmissionComparisonController@processCSV'
)->name('modules.assessments.compare.processCSV');

// ASSESSMENT TESTS

Route::get(
    '/modules/{module}/assessments/{assessment}/tests',
    'AssessmentController@showTests'
)->name('modules.assessments.showTests');

Route::get(
    '/modules/{module}/assessments/{assessment}/tests/edit',
    'AssessmentController@editTests'
)->name('modules.assessments.editTests');

Route::post(
    '/modules/{module}/assessments/{assessment}/tests',
    'AssessmentController@storeTests'
)->name('modules.assessments.storeTests');

Route::get(
    '/modules/{module}/assessments/{assessment}/tests/yaml',
    'AssessmentController@exportTestsToYAML'
)->name('modules.assessments.exportTestsToYAML');

Route::get(
    '/modules/{module}/assessments/{assessment}/tests/yaml/import',
    'AssessmentController@showImportTestsFromYAML'
)->name('modules.assessments.showImportTestsFromYAML');

Route::post(
    '/modules/{module}/assessments/{assessment}/tests/yaml/import',
    'AssessmentController@importTestsFromYAML'
)->name('modules.assessments.importTestsFromYAML');

// PROGRESS CHART

Route::get(
    '/modules/{module}/assessments/{assessment}/progress/chart',
    'AssessmentController@viewProgressChart'
)->name('modules.assessments.viewProgressChart');

Route::get(
    '/modules/{module}/assessments/{assessment}/progress/stats',
    'AssessmentController@jsonProgressStats'
)->name('modules.assessments.jsonProgressChart');

Route::get(
    '/modules/{module}/assessments/{assessment}/progress/entries/{className}/{testName}/{status}',
    'AssessmentController@jsonClassTestStatus'
)->name('modules.assessments.jsonClassTestStatus');

// SINGLE SUBMISSION MANAGEMENT

Route::post(
    '/modules/{module}/assessments/{assessment}/storeSubmission',
    'AssessmentController@storeSubmission'
)->name('modules.assessments.storeSubmission');

Route::get(
    '/modules/{module}/submissions/{submission}',
    'AssessmentSubmissionController@show'
)->name('modules.submissions.show');

Route::post(
    '/modules/{module}/submissions/{submission}/rerun',
    'AssessmentSubmissionController@rerun'
)->name('modules.submissions.rerun');

Route::delete(
    '/modules/{module}/submissions/{submission}',
    'AssessmentSubmissionController@destroy'
)->name('modules.submissions.destroy');

// HELP PAGES

Route::view(
    '/help/markdown/conditionals',
    'help.markdown_conditionals'
)->name('help.markdown.conditionals');

webapp/app/Http/Controllers/API/JobController.php
<?php

/**
*  Copyright 2021 Aston University
*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
*
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace App\Http\Controllers\API;


use App\Events\MavenBuildJobStatusUpdated;
use App\Http\Controllers\Controller;
use App\Jobs\MarkSubmissionJob;
use App\Zip\ExtendedZipArchive;
use App\ZipSubmission;
use Illuminate\Http\Request;
use Illuminate\Log\Logger;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;

class JobController extends Controller
{
    use GeneratesJSON;

    const MAX_BUILD_RESULTS_SIZE_KB = 10000;

    const DOWNLOAD_COMBINED_CAP_PREFIX = 'jobs:download_build_zip:';
    const STORE_RESULTS_CAP_PREFIX = 'jobs:store_results:';

    /**
     * Controller constructor.
     */
    public function __construct()
    {
        $this->middleware(['auth:sanctum', 'job.api.range']);
    }

    /**
     * Retrieves a ZIP with the combination of the student's submission and the file
     * overrides, ready to be built to produce the automated feedback. This can use
     * either a general personal access token (e.g. from a tutor in the module), or
     * a limited single-use token (e.g. from a Kube job).
     */
    public function downloadBuildZip(Request $request, ZipSubmission $job) {
        if (!$request->user()->tokenCan(self::DOWNLOAD_COMBINED_CAP_PREFIX . $job->id)) {
            return $this->jsonForbidden('Invalid token.',
            'Token does not have the capability to download a combined ZIP for this submission.'
            );
        }
        $this->revokeSingleUseToken($request);

        $canViewJob = $request->user()->can('view', $job);
        $canViewModelSolution = !$job->assessment
            || $request->user()->can('viewModelSolution', $job->assessment->assessment);
        if (!$canViewJob || !$canViewModelSolution) {
            return $this->jsonForbidden('Insufficient permissions.',
                'You do not have the necessary permissions to download the build ZIP.');
        }

        try {
            // GENERATE ZIP
            $buildWD = $job->setUpWorkingDirectory();
            $tempPath = tempnam(sys_get_temp_dir(), 'combined');
            ExtendedZipArchive::zipTree($buildWD, $tempPath, \ZipArchive::CREATE | \ZipArchive::OVERWRITE);
        } catch (\Exception $e) {
            if (isset($tempPath) && file_exists($tempPath)) {
                unlink($tempPath);
            }

            Logger::error($e);
            return $this->jsonServerError(
                'Error while generating ZIP file.',
                'There was a problem generating the combined ZIP file - please contact the system administrator.');
        }

        return response()->download($tempPath, 'build-sub_' . $job->id . '.zip')->deleteFileAfterSend(true);
    }

    /**
     * Replaces the results of this job from those of the provided ZIP, giving the job the provided status code.
     *
     * @see ZipSubmission::collectResultsFromZIP() for details on the expected format of the ZIP file.
     */
    public function storeResults(Request $request, ZipSubmission $job) {
        if (!$request->user()->tokenCan(self::STORE_RESULTS_CAP_PREFIX . $job->id)) {
            return $this->jsonForbidden('Invalid token.',
                'Token does not have the capability to upload build results for this submission.'
            );
        }
        $this->revokeSingleUseToken($request);

        $canViewJob = $request->user()->can('view', $job);
        $canUploadResults = $request->user()->can('storeResults', $job);
        if (!$canViewJob || !$canUploadResults) {
            return $this->jsonForbidden('Insufficient permissions.',
                'You do not have the necessary permissions to upload build results.');
        }

        $validator = Validator::make($request->all(), [
            'resultsfile' => ['required', 'file', 'mimes:zip', 'max:' . self::MAX_BUILD_RESULTS_SIZE_KB],
            'statuscode' => ['required', 'numeric', 'integer', 'min:0' ],
        ]);
        if ($validator->fails()) {
            return $this->jsonInvalidRequest($validator);
        }

        $resultsFile = $request->file('resultsfile');
        $statusCode = (int) $request->get('statuscode');
        DB::transaction(function() use ($job, $resultsFile, $statusCode) {
            $job->status = $statusCode;
            $job->save();

            event(new MavenBuildJobStatusUpdated($job));
            Log::info("Maven build for '"
                . $job->diskPath
                . "' completed with return value $statusCode");

            $job->resultFiles()->delete();
            $job->collectResultsFromZIP($resultsFile);
        });

        if ($job->assessment) {
            MarkSubmissionJob::dispatch($job->assessment->id);
        }
        return $this->jsonResponse('OK');
    }

    /**
     * @param Request $request
     */
    private function revokeSingleUseToken(Request $request): void
    {
        if (!$request->user()->tokenCan('*')) {
            // This is a single-capability, one-time use token: revoke it
            $request->user()->currentAccessToken()->delete();
        }
    }
}

webapp/resources/views/jobs/create.blade.php
@php
    /**
     *  Copyright 2020 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@section('title', __('Create Raw Job'))

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">{{ __('Create Raw Job') }}</h2>
            <form method="POST" action="{{ route('jobs.store') }}" enctype="multipart/form-data">
                @csrf
                <x-file-upload-field :fieldName="'jobfile'" :required="true" :promptText="'Choose ZIP file'"
                                     :accept="'application/zip,.zip'"/>
                <div class="text-center">
                    <input class="btn btn-primary" type="submit" value="{{ __('Submit') }}">
                    <a role="button" class="btn btn-secondary" href="{{ route('jobs.index') }}">{{ __('Cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
@endsection

webapp/resources/views/jobs/index.blade.php
@php
    /**
     *  Copyright 2020-2021 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@php
/**
 * @var \App\ZipSubmission[]|Illuminate\Pagination\LengthAwarePaginator $jobs
 * @var integer $page
 */
@endphp

@section('title', __('Jobs'))

@section('content')
        <div class="row justify-content-center">
            <div class="col-md-8">
                @can('create', \App\ZipSubmission::class)
                    <a role="button" class="btn btn-primary" href="{{ route('jobs.create') }}">{{ __('Create Raw Job') }}</a>
                @endcan

                @if($jobs->count() > 0)
                    @can(\App\Policies\ZipSubmissionPolicy::DELETE_ANY_PERMISSION)
                            <button id="deleteManyModalButton" type="button" class="btn btn-danger" data-toggle="modal"
                                    data-target="#deleteManyModal" data-af-row-select-table="#jobsTable">
                                {{ __('Delete selected') }}
                            </button>

                            <x-modal-confirm :id="'deleteManyModal'" :title="'Delete checked submissions?'">
                                <x-slot name="body">
                                    {{ __('Do you wish to delete the checked submissions?') }}
                                </x-slot>
                                <form class="form-inline custom-control-inline mr-0"
                                      action="{{ route('jobs.destroyMany') }}"
                                      method="POST" id="deleteManyForm">
                                    @csrf
                                    @method('DELETE')
                                    <input class="btn btn-danger" type="submit" value="{{ __('Delete') }}"/>
                                </form>
                            </x-modal-confirm>
                        @endcan

                    <table class="table table-hover mt-4 af-row-select-table" id="jobsTable">
                        <thead>
                            <th scope="col"><input type="checkbox" class="af-row-select-all" /></th>
                            <th scope="col">{{ __('Filename') }}</th>
                            <th scope="col">{{ __('Created') }}</th>
                            <th scope="col">{{ __('Author') }}</th>
                            <th scope="col">{{ __('Status') }}</th>
                        </thead>
                        <tbody>
                        @foreach ($jobs as $job)
                            <tr>
                                <td><input type="checkbox" class="af-row-select" value="{{ $job->id }}"/></td>
                                <td><a href="{{ route('jobs.show', ['job' => $job->id, 'backPage' => $page]) }}">{{ $job->filename }}</a></td>
                                <td>{{ $job->created_at }}</td>
                                <td>{{ $job->user->name }}</td>
                                <x-job-status-cell :job="$job"/>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $jobs->links() }}
                @else
                    <div class="alert alert-warning mt-2" role="alert">
                        {{ __('No jobs have been submitted yet!') }}
                    </div>
                @endif
            </div>
        </div>
@endsection

@section('extrajs')
    <script type="application/javascript">
        $('#deleteManyForm').on('submit', () => {
            $('#jobsTable input.af-row-select:checked').each((i, e) => {
                $('<input type="hidden">').attr({
                    name: 'jobIDs[]',
                    value: e.value
                }).appendTo('#deleteManyForm');
            });
            return true;
        });
    </script>
@endsection

webapp/resources/views/jobs/show.blade.php
@php
    /**
     *  Copyright 2020-2021 Aston University
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
@endphp

@extends('layouts.app')

@php
/**
 * @var \App\ZipSubmission $job
 * @var \App\BuildResultFile[]|Illuminate\Pagination\LengthAwarePaginator $results
 * @var integer $backPage
 */
@endphp

@section('title'){{ __('Job :id', ['id' => $job->id]) }}@endsection

@section('content')
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2>{{ __('Details of Job #:jobid', ['jobid' => $job->id]) }}</h2>

                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                        <tr>
                            <th scope="row">{{ __('File') }}</th>
                            <td><a href="{{ route('jobs.download', $job->id) }}">{{ $job->filename }}</a></td>
                        </tr>
                        <tr>
                            <th scope="row">{{ __('Author') }}</th>
                            <td>{{ $job->user->name }} - <a href="mailto:{{ $job->user->email }}">{{ $job->user->email }}</a></td>
                        </tr>
                        @if($job->user_id != $job->submitter_user_id)
                            <tr>
                                <th scope="row">{{ __('Submitter') }}</th>
                                <td>{{ $job->submitter->name }} - <a href="mailto:{{ $job->submitter->email }}">{{ $job->submitter->email }}</a></td>
                            </tr>
                        @endif
                        <tr>
                            <th scope="row">{{ __('Status') }}</th>
                            <x-job-status-cell :job="$job" :reloadOnFinish="true"/>
                        </tr>
                        <tr>
                            <th scope="row">{{ __('Created at') }}</th>
                            <td>{{ $job->created_at }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{ __('Updated at') }}</th>
                            <td>{{ $job->updated_at }}</td>
                        </tr>
                        @if($job->sha256 != \App\ZipSubmission::SHA256_PENDING)
                            <tr>
                                <th scope="row">{{ __('SHA-256') }}</th>
                                <td>{{ $job->sha256 }}</td>
                            </tr>
                        @endif
                        @if($job->modelSolution)
                            <tr>
                                <th scope="row">{{ __('Model solution for') }}</th>
                                <td>
                                    <x-teaching-module-item-link :item="$job->modelSolution->assessment->usage"/>
                                    - <x-model-solution-version-description :modelSolution="$job->modelSolution"/>
                                </td>
                            </tr>
                        @endif
                        @if($job->assessment)
                            <tr>
                                <th scope="row">{{ __('Submission for') }}</th>
                                <td><x-teaching-module-item-link :item="$job->assessment->assessment->usage"/></td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>

                <div class="text-center">
                    @can('delete', $job)
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">{{ __('Delete') }}</button>
                    @endcan
                    @if($backPage)
                        <a href="{{ route('jobs.index', ['page' => $backPage]) }}" class="btn btn-secondary">{{ __('Back') }}</a>
                    @endif
                </div>

                @can('delete', $job)
                    <x-modal-confirm :id="'deleteModal'" :title="__('Delete Job?')">
                        <x-slot name="body">
                            {{ __('Do you want to delete Job #:jobid and all its files?', ['jobid' => $job->id]) }}
                        </x-slot>
                        <form class="form-inline custom-control-inline mr-0"
                              action="{{ route('jobs.destroy', $job->id) }}"
                              method="POST">
                            @csrf
                            @method('DELETE')
                            <input class="btn btn-danger" type="submit" value="{{ __('Delete') }}"/>
                        </form>
                    </x-modal-confirm>
                @endcan

                @if($results->isEmpty())
                    <div class="alert alert-warning mt-2" role="alert">
                        {{ __('This job has not produced any result files yet') }}
                    </div>
                @else
                    <h3>{{ __('Result files') }}</h3>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th scope="col">{{ __('Source') }}</th>
                                <th scope="col">{{ __('Filename') }}</th>
                                <th scope="col">{{ __('MIME type') }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($results as $r)
                                <tr>
                                    <td>{{ $r->source }}</td>
                                    <td><a href="{{ $r->url($job) }}">{{ $r->originalPath }}</a></td>
                                    <td>{{ $r->mimeType }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{ $results->links() }}
                @endif
            </div>
        </div>
@endsection